### PR TITLE
deployment strategy

### PR DESCRIPTION
**Pull request by spencer1248**

### CODE REVIEW

**Comment by ktravers** [comment]
👍

**Comment by snags88** [comment]
@spencer1248 feature deployment as in feature launching to different populations ya?

**Comment by spencer1248** [comment]
Whatever it may entail, it can be population scoping, or it can be how and what order to turn services on and off so that stuff doesn't break. Intentionally vague.

**Comment by spencer1248** [comment]
I'll clarify the vagueness as being intentional.

**Comment by spencer1248** [comment]
@snags88 I updated the document to define what is meant by "deployment strategy".

**Comment by snags88** [comment]
@spencer1248 looks great! thanks for the update

**Pull request merged**
